defmodule Euler.Exercise_012 do
  @moduledoc """
  The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
  1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

  The first 10 terms would be 1, 3, 6, 10, 15, 21, 28, 36, 45, 55

  We can see that 28 is the first triangle number to have over five divisors.

  What is the value of the first triangle number to have over five hundred divisors?
  """

  @doc """
  First solution, to be discarded:

    def brute_force(n \\ 500) do
      Stream.iterate(1, &(&1 + 1))
      |> Stream.map(&triangle/1)
      |> Stream.map(&{&1, &1 |> factors() |> length()})
      |> Stream.drop_while(fn {_a, b} -> b < n end)
      |> Enum.take(1)
    end

  """

  def solution(n \\ 500) do
    triangle()
    |> Stream.drop_while(fn x -> d(x) < n end)
    |> Enum.take(1)
  end

  @spec d(any()) :: any()
  def d(n) do
    primefactors(n)
    |> Enum.reduce(Map.new(), fn x, acc ->
      if Map.has_key?(acc, x), do: Map.update!(acc, x, &(&1 + 1)), else: Map.put(acc, x, 1)
    end)
    |> then(fn x -> Map.values(x) end)
    |> Enum.reduce(1, &((&1 + 1) * &2))
  end

  def primefactors(n) do
    Stream.unfold({n, 2}, fn {n, a} ->
      cond do
        n == 1 -> nil
        rem(n, a) == 0 -> {a, {div(n, a), a}}
        true -> {0, {n, a + 1}}
      end
    end)
    |> Stream.reject(&(&1 == 0))
    |> Enum.to_list()
  end

  # Stream
  defp triangle() do
    Stream.iterate(1, &(&1 + 1)) |> Stream.map(fn x -> div(x * (x + 1), 2) end)
  end

  # Recursive function
#  defp triangle(1), do: 1
#  defp triangle(n), do: n + triangle(n - 1)

end
